//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverDetail()
        {
            this.TransportDetail = new HashSet<TransportDetail>();
        }
    
        public int DriverId { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> RouteId { get; set; }
        public System.DateTime DateAvailable { get; set; }
    
        public virtual RouteDetail RouteDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportDetail> TransportDetail { get; set; }
    }
}
