//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportDetail
    {
        public int TransportId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public DateTime Date { get; set; }
        public int Passengers { get; set; }
    
        public virtual DriverDetail DriverDetail { get; set; }
        public virtual RouteDetail RouteDetail { get; set; }
        public virtual TypeDetail TypeDetail { get; set; }
    }
}
